### ISSUE TITLE
Can’t work at mobile

### ISSUE THREAD

**Issue by forestluch** [iBicha/UnityYoutubePlayer#101]
Usage:

GetComponent<VideoPlayer>().PlayYoutubeVideoAsync("https://www.youtube.com/watch?v=1PuGuqpHQGo");

it is work perfect at Mac and PC but build to mobile (Android, iOS both) they show an error and can't work

Exception: HTTP/1.1 404 Not Found
ResponseError:<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <title>Heroku | Application Error</title>...

How to solve that? thanks.

**Comment by iBicha** [comment]
The public instance that serves non-desktop is no longer available.
Please see my comment https://github.com/iBicha/UnityYoutubePlayer/issues/96#issuecomment-1422901605
