### ISSUE TITLE
Error "HTTP/1.1 404 Not Found" only on Android/iOs using our own Heroku instance

### ISSUE THREAD

**Issue by franstuka** [iBicha/UnityYoutubePlayer#102]
Hi I'm trying to reproduce videos in Android and IOS. In Desktop, Unity Editor and web (even in phone) works fine.

I have Deploied the server in Heroku, and setted the _YoutubeDl.ServerUrl_ propierty to my own server before making any calls.

In the videoplayer GO, the "cli" is setted to Yt Dlp, (however i tried both options without success)

Checking the logcat, I get this error:

```
> ERROR HTTP/1.1 404 Not Found
> ResponseError:<!DOCTYPE html>
> <html lang="en">
> <head>
> <meta charset="utf-8">
> <title>Error</title>
> </head>
> <body>
> <pre>Cannot GET //v1/video</pre>
> </body>
> </html>
```

**Comment by iBicha** [comment]
When setting the YoutubeDl.ServerUrl, remove the trailing `/`
