### ISSUE TITLE
It recently stopped working for Oculus Android and about 2 months ago if it was working perfectly

### ISSUE THREAD

**Issue by dclaresnri** [iBicha/UnityYoutubePlayer#103]
It recently stopped working for Oculus Android, and about 2 months ago, it worked perfectly, no changes have been made in this part, and now it stopped working and still working well for PC. I added some logs, and here is the error it throws,

any idea what it could be?
Greetings

[logs.txt](https://github.com/iBicha/UnityYoutubePlayer/files/10924932/logs.txt)

**Comment by iBicha** [comment]
Hi @dclaresnri , please see https://github.com/iBicha/UnityYoutubePlayer/issues/96#issuecomment-1422901605
