### ISSUE TITLE
Alternative to Heroku server ?

### ISSUE THREAD

**Issue by antoinenisoli** [iBicha/UnityYoutubePlayer#104]
Hello, 

I tried to play youtube videos in my android app through my own Heroku server but it seems that deploy the server online is not free anymore. We already use a custom server to manage data for our mobile applications, but i don't see how i can use that server to host youtube videos instead of Heroku. Do you know a good free alternative to Heroku or a tutorial to implement youtube-dl on our own server and then make the plugin to work ?

For more precision, i have the "Exception: HTTP/1.1 404 Not Found ResponseError:<!DOCTYPE html>" error log when i try to start a youtube video on android, but from what i've seen this is a known issue since the local server has been deleted.

**Comment by iBicha** [comment]
Closing since we're using Invidious in version 3.0.0
Please refer to Invidious setup guide https://docs.invidious.io/installation
A docker compose if available if you need it
