### ISSUE TITLE
Issue with 360 videos.

### ISSUE THREAD

**Issue by jayaram9877** [iBicha/UnityYoutubePlayer#108]
**STEPS TO REPRODUCE**

1. Donwlaod the  github repo 
2.  Run panaromic scene in editor
3. Make sure is360 is enabled in Youtubeplayer ccomponent.

 **OUTPUT**

1. Black screeen
2. Video dosent play

> Warning: Color primaries 0 is unknown or unsupported by WindowsMediaFoundation. Falling back to default may result in color shift. https://rr5---sn-gwpa-20ue.googlevideo.com/videoplayback?expire=1695768672&ei=AAwTZev0MZTK4-EP_JW1gAM&ip=49.47.235.133&id=o-AMayKFLr5UkCrpT6mJw2Vb9LSzqQgLhdA7moM-IBbbUx&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C271%2C278%2C313%2C394%2C395%2C396%2C397%2C398%2C399&source=youtube&requiressl=yes&mh=OW&mm=31%2C29&mn

**EXPECTED OUTPUT**
1. Play youtube video in skybox.

**Comment by jayaram9877** [comment]
In MAC pro m1 & IOS even after using own server video is not playing.

**Comment by iBicha** [comment]
Closing this issue - with version 3 I removed support for 360 videos. They are too cumbersome, we still don't have a proper shader to display them, and they won't have audio until Unity's video player can support muxed videos (like DASH or HLS)

**Comment by iBicha** [comment]
PS: I'm not saying this is not a valid thing to ask - but this is a bug issue for a feature that was removed. It's more appropriate  to create a feature request issue if anyone still needs this feature.
