### ISSUE TITLE
Many of the videos cannot be played.

### ISSUE THREAD

**Issue by Memane** [iBicha/UnityYoutubePlayer#11]
Hello,
I am having a lot of problems a lot of videos cannot be played, here is the error message I get.

```
ArgumentNullException: Value cannot be null.
Parameter name: value
Newtonsoft.Json.Linq.Extensions.Value[T,U] (System.Collections.Generic.IEnumerable`1[T] value) (at <97722d3abc9f4cf69f9e21e6770081b3>:0)
Newtonsoft.Json.Linq.Extensions.Value[U] (System.Collections.Generic.IEnumerable`1[T] value) (at <97722d3abc9f4cf69f9e21e6770081b3>:0)
YoutubeExplode.Internal.Parsers.PlayerResponseParser+StreamInfoParser.ParseUrl () (at Assets/Memane Test/TestYoutube/YoutubeExplode/Internal/Parsers/PlayerResponseParser.cs:101)
YoutubeExplode.YoutubeClient+<GetVideoMediaStreamInfosAsync>d__26.MoveNext () (at Assets/Memane Test/TestYoutube/YoutubeExplode/YoutubeClient.Video.cs:97)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <fb001e01371b4adca20013e0ac763896>:0)
YoutubePlayer.YoutubePlayer+<PlayVideoAsync>d__9.MoveNext () (at Assets/Memane Test/TestYoutube/YoutubePlayer/Scripts/YoutubePlayer.cs:64)
UnityEngine.Debug:LogException(Exception)
YoutubePlayer.<PlayVideoAsync>d__9:MoveNext() (at Assets/Memane Test/TestYoutube/YoutubePlayer/Scripts/YoutubePlayer.cs:81)
UnityEngine.UnitySynchronizationContext:ExecuteTasks()
```

One starts well but the other does not work
Works : https://www.youtube.com/watch?v=8QgnbY7VoeM
Don't work : https://www.youtube.com/watch?v=wiEiohrXI4U

I'm not sure where to start to resolve this problem, that's why I'm coming to you.

Thank you for your help.

**Comment by Memane** [comment]
OK, I have the impression that it is because of the royalties that it does that?
Is there a way to get past that?

**Comment by iBicha** [comment]
Thanks for posting the issue.
I tested the video with the latest release #10 but I'm still experiencing this issue.
It is best to open an issue in https://github.com/Tyrrrz/YoutubeExplode to get better help (I would recommend testing the video on the latest release of YoutubeExplode explode first, to make sure it actually doesn't work).

**Comment by Memane** [comment]
OK, thanks.
I see to use something else because if it happens in production it's not going to be joy.

**Comment by iBicha** [comment]
> OK, thanks.
> I see to use something else because if it happens in production it's not going to be joy.

You need to know that, even if it's at a working state in production, if youtube make changes to their website, any Youtube library can/will probably break. Anyhow, this is not the intended way to use Youtube

**Comment by iBicha** [comment]
Please reopen issue if problem persists. thanks
