### ISSUE TITLE
General access denied error

### ISSUE THREAD

**Issue by Muhammad-Asim-Dev** [iBicha/UnityYoutubePlayer#116]
WindowsVideoMedia error 0x80070005 while reading https://invidious.fdn.fr/latest_version?id=5jlI4uzZGjU

Context: MFCreateSourceReaderFromURL
Error details: General access denied error

Track types:

VideoPlayer cannot play url : https://invidious.fdn.fr/latest_version?id=5jlI4uzZGjU

Cannot read file.

**Comment by iBicha** [comment]
Thanks for reporting - this can happen on some videos (usually more popular videos, music videos, etc) where YouTube detects that you're requesting the video from one location (in this case https://invidious.fdn.fr, so France) but playing the video from a different location.
You can try to choose a different instance (select the `Invidious Instance` component, and set the Invidious instance type to custom, and choose a different url from https://api.invidious.io - or host your own server)

I will attempt to improve this by adding proxying videos on failure.

**Comment by iBicha** [comment]
I have merged a fix - but it is tricky because the Unity VideoPlayer takes a long time trying to load the video before it fails.
I will keep an eye on it for a while before I release a new version, but you can get the fix from the main branch

**Comment by iBicha** [comment]
Fixed in [v3.3.0](https://github.com/iBicha/UnityYoutubePlayer/releases/tag/v3.3.0)

**Comment by Muhammad-Asim-Dev** [comment]
Thanks it worked using proxy
