### ISSUE TITLE
Download video button doesn't work

### ISSUE THREAD

**Issue by conan1987** [iBicha/UnityYoutubePlayer#13]
Hi
I try to download the video but it gives me these errors:
NullReferenceException: Object reference not set to an instance of an object
YoutubeExplode.Internal.Parsers.VideoWatchPageParser.ParseDescription () (at Assets/YoutubeExplode/Internal/Parsers/VideoWatchPageParser.cs:29)
YoutubeExplode.YoutubeClient+<GetVideoAsync>d__36.MoveNext () (at Assets/YoutubeExplode/YoutubeClient.Video.cs:37)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <599589bf4ce248909b8a14cbe4a2034e>:0)
YoutubePlayer.YoutubePlayer+<DownloadVideoAsync>d__10.MoveNext () (at Assets/YoutubePlayer/Scripts/YoutubePlayer.cs:101)
UnityEngine.Debug:LogException(Exception)
YoutubePlayer.<DownloadVideoAsync>d__10:MoveNext() (at Assets/YoutubePlayer/Scripts/YoutubePlayer.cs:132)
UnityEngine.UnitySynchronizationContext:ExecuteTasks()

and

ArgumentNullException: Value cannot be null.
Parameter name: closedCaptionTrack
YoutubePlayer.Extensions.ToSRT (YoutubeExplode.Models.ClosedCaptions.ClosedCaptionTrack closedCaptionTrack) (at Assets/YoutubePlayer/Scripts/Extensions.cs:80)
YoutubePlayer.DownloadYoutubeVideo+<Download>d__5.MoveNext () (at Assets/YoutubePlayer/Scripts/DownloadYoutubeVideo.cs:39)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at C:/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:114)
UnityEngine.UnitySynchronizationContext:ExecuteTasks()

What can i do ? i didn't edit any of your files so the line numbers are the same

**Comment by iBicha** [comment]
This should be fixed by now, please reopen issue if it is not solved.
