### ISSUE TITLE
18 itag max quality formatStreams

### ISSUE THREAD

**Issue by scorp2007** [iBicha/UnityYoutubePlayer#130]
Hello. Why formatStreams returns only result 18? I understand this is the best video with sound? And it corresponds to 360 or 480 quality. I tried both the public server and my own, both are the same. How can I get a video with sound at least as indicated result 22 (720p)? Thank you.

**Comment by iBicha** [comment]
According to many people who investigated this, YouTube started discontinuing format 22 (perhaps it is completely gone by now).
In the future, it might be not possible to play videos 720p+ without support for HLS/DASH (which is currently not supported by the default VideoPlayer component, but is supported by 3rd party paid assets)

**Comment by scorp2007** [comment]
> According to many people who investigated this, YouTube started discontinuing format 22 (perhaps it is completely gone by now). In the future, it might be not possible to play videos 720p+ without support for HLS/DASH (which is currently not supported by the default VideoPlayer component, but is supported by 3rd party paid assets)

that is, at the present time, in order to reproduce good quality in Unity, I need to launch sound and video separately? All adaptive high-quality formats are DASH and there the video is separate from the sound?

**Comment by iBicha** [comment]
Yes all the higher quality streams are video only or audio only, not both.
You could try playing both yourself, but mostly you'll run into synchronization issues.
This is why a DASH player is needed (it will synchronize for you, and adjusts quality based on internet speed)

**Comment by scorp2007** [comment]
> Yes all the higher quality streams are video only or audio only, not both. You could try playing both yourself, but mostly you'll run into synchronization issues. This is why a DASH player is needed (it will synchronize for you, and adjusts quality based on internet speed)

ah, it's sad to hear, earlier you said that there are some paid players for Unity that work with DASH, I wonder what these assets are and do they work in WebGL?

**Comment by iBicha** [comment]
I can't vouch for any because I haven't tried them myself and wouldn't know if they worked as advertised, but look at the unity asset store

**Comment by scorp2007** [comment]
> I can't vouch for any because I haven't tried them myself and wouldn't know if they worked as advertised, but look at the unity asset store

ok, thank you very much for explaining the situation
