### ISSUE TITLE
Does it work with WebGL?

### ISSUE THREAD

**Issue by Yanfundi** [iBicha/UnityYoutubePlayer#16]
Hi, I wanted to use this plugins and build it on Unity WebGL, does it work? im using Unity 2018.4.23f1. Thank you

**Comment by iBicha** [comment]
Thanks for the suggestion. I haven't tried WebGL, but I assume this doesn't work on it. https://docs.unity3d.com/Manual/webgl-networking.html
Needs a different approach, and usages of `UnityWebRequest`

**Comment by iBicha** [comment]
After investigating different approaches, I see that there's no easy way to support webgl, because of CORS (you'd get an access origin error).
The only solution I see is to implement a server that downloads the video for you, and streams it back, which is outside of the scope of this repo.
