### ISSUE TITLE
Live Streams ussing an HLS Player

### ISSUE THREAD

**Issue by parsec3d** [iBicha/UnityYoutubePlayer#18]
Would be great if you can add support to an HLS player like AVPro .

**Comment by iBicha** [comment]
Thanks for the suggestion. I'm not sure if this is possible without processing the video stream. If it is, we can find a way to implement it. But if it requires some kind of video processor / encoder, that will probably be outside of the scope of this project.

**Comment by iBicha** [comment]
There's no out of the box support for playing m3u8 streams manifest (which is what youtube live is based on).
However, You can use UnityYoutubePlayer to parse the video stream using 
```
var rawUrl = YoutubePlayer.GetRawVideoUrlAsync("<LIVE_VIDEO_URL>");
```
And pass the url to a third party video player who's capable of playing such format (I'm not familiar with AVPro specifically)
