### ISSUE TITLE
How to start at specific Minutes/Seconds

### ISSUE THREAD

**Issue by waheed11** [iBicha/UnityYoutubePlayer#22]
Hello,
I tried to start the video at specific minutes and seconds, for example:

https://www.youtube.com/watch?v=sPyAQQklc1s 

To start the above URL at 1:30, I used the below URL:

http://www.youtube.com/watch?v=sPyAQQklc1s&t=1m30s

It works fine in the browser but when I add it in "YouTube Player", it allows takes me to the start point (s=0) 

Please how I can solve this?  Thank you

**Comment by iBicha** [comment]
Hi,
Use the VideoPlayer API (set [VideoPlayer.time](https://docs.unity3d.com/ScriptReference/Video.VideoPlayer-time.html) to the time you want)
