### ISSUE TITLE
Slow video prepare

### ISSUE THREAD

**Issue by DaniloCCP** [iBicha/UnityYoutubePlayer#26]
I'm using your great asset in an android app to play a list of youtube videos
The loading time using PlayVideoAsync is very slow (above 10 seconds). I would like to start the video.prepare() ahead of time, but there is no such method, only PlayVideoAsync(). There is a proper way to avoid long waiting time?

**Comment by iBicha** [comment]
That's slow indeed. This has a lot of variables in place: internet quality, parsing time of the youtube page (done by YoutubeExplode), and the warmup of the player.
Need to do some investigation to see what time can be shaved off, but tbh I don't know if I will have the time to do that in the near future.

**Comment by iBicha** [comment]
Added a new version with a async prepare method. While the new version might even take longer because of the additional web request, but it allows to have the video ready to play.
