### ISSUE TITLE
I m using latest version first day it was working fine currently  it starts showing me HTTP/1.1 500 Internal Server Error

### ISSUE THREAD

**Issue by Kavita315** [iBicha/UnityYoutubePlayer#33]
Hi @iBicha 
using version 1.3.2 plz help

Exception: HTTP/1.1 500 Internal Server Error
ResponseError:{"error":"Command failed: /app/tools/bin/youtube-dl -f "best" --dump-json https://youtu.be/aJbYWaDfgf4\nERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.\n","stderr":"ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.\n","stdout":""}
Screenshot 2021-02-01 at 10 49 13 AM

**Comment by iBicha** [comment]
As you can see, it says `HTTP Error 429: Too Many Requests `.
At this point, a lot of users are using this package, and everyone is using a free heroku instance.
Instance located at: https://unity-youtube-dl-server.herokuapp.com/v1/video?url=https://www.youtube.com/watch?v=1PuGuqpHQGo
You should consider hosting [youtube-dl-server](https://github.com/iBicha/youtube-dl-server) yourself.

**Comment by iBicha** [comment]
Added more instructions to read me about self hosting.
