### ISSUE TITLE
VideoPlayer cannot play url: ...

### ISSUE THREAD

**Issue by baststar** [iBicha/UnityYoutubePlayer#35]
I tested this (maybe) nice YoutubePlayer, but i only get the error:

```
WindowsVideoMedia error 0xc00d36c4 while reading https://www.youtube.com/watch?v=tTlwByBuJ1k
VideoPlayer cannot play url: https://www.youtube.com/watch?v=tTlwByBuJ1k
```

New Unity-Project with:
Unity 2021.1.0b5.1871 Personal DX11
Windows 10 10.0.19042 
HEVC-Extension not installed... (If this is a dependency for YT-Videos - how would i deploy a game where you can watch YT-Videos?)

Tested also with Unity 2018.4.31f1 Personal DX11

Just added the dependencies, added the videoplayer-gameobject, changed source to URL, inserted a youtube-link and pressed play.
:(

**Comment by iBicha** [comment]
You need to set the url in the [YoutubePlayer](https://github.com/iBicha/UnityYoutubePlayer/blob/master/Packages/com.ibicha.youtube-player/Runtime/YoutubePlayer.cs) component, not the `VideoPlayer` component.

**Comment by baststar** [comment]
Ahh thank you!!
