### ISSUE TITLE
Download Subtittles

### ISSUE THREAD

**Issue by olidepalma** [iBicha/UnityYoutubePlayer#37]

**Comment by olidepalma** [comment]
Hello! Thanks for the plugin. I am trying to use it to be able to download the video with subtitles. I have seen that for this it is necessary to use ffmpeg or avconv. Does Youtube-dl server already have them included?

**Comment by iBicha** [comment]
If you mean that you want to "merge" the video file with the subtitles, then yes, you need ffmpeg, and no, Youtube-dl server does not have that.
If there's a need to download only the subtitles to Unity (to show them on screen for example) then using the timedtext api could be simple. E.g.
List subtitles: https://www.youtube.com/api/timedtext?type=list&v=a8uyilHatBA
Get english: http://video.google.com/timedtext?v=lT3vGaOLWqE&&lang=en
You can also specify the format with http://video.google.com/timedtext?v=lT3vGaOLWqE&&lang=en&fmt=vtt

And then it's a matter of parsing the response (parsing xml in C#) reading the times and syncing it with the time of the video player.

**Comment by iBicha** [comment]
Since we stopped using youtube-dl, this feature is no longer in scope.
Currently version 3.0.0 is missing subtitles, but they can be implemented using Invidious API https://docs.invidious.io/api/#get-apiv1captionsid
If this feature is still important to you, please create an issue. Thanks
