### ISSUE TITLE
Youtube Player: NotSupportedException: No supported streams in youtube video

### ISSUE THREAD

**Issue by mhadji05** [iBicha/UnityYoutubePlayer#4]
I m trying to play Player.unity scene but i get error

NotSupportedException: No supported streams in youtube video '1PuGuqpHQGo'
YoutubePlayer.YoutubePlayer+<PlayVideoAsync>d__9.MoveNext () (at Assets/YoutubePlayer/Scripts/YoutubePlayer.cs:67)
UnityEngine.Debug:LogException(Exception)
YoutubePlayer.<PlayVideoAsync>d__9:MoveNext() (at Assets/YoutubePlayer/Scripts/YoutubePlayer.cs:81)
UnityEngine.UnitySynchronizationContext:ExecuteTasks()

I need to play stream video from youtube!

**Comment by elblogbruno** [comment]
Please update the YouTube extractor library to the latest version!

**Comment by shisharma** [comment]
Hi 
Updating the libraries does the trick but now I get the error that states: 

Player failed to load "https://r2---sn-ci5gup-pmjk.googlevideo.com/videoplayback?id=o-AJw-ijWFZXlTKnVD5N4gwvyQuT6IZTuXA74p1fpTPn6A&itag=22&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-ci5gup-pmjk%2Csn-ci5gup-qxae7&ms=au%2Crdu&mv=m&pl=45&ei=0YPrXIDzIaKq8QOyk7uwCg&initcwndbps=186250&mime=video%2Fmp4&ratebypass=yes&dur=1413.073&lmt=1558327365183090&mt=1558938432&fvip=2&c=WEB&txp=5535432&ip=2401%3A4900%3A30b6%3Afc35%3Ae4ee%3Ac11a%3Ad33d%3A5fd4&ipbits=0&expire=1558960177&sparams=ip%2Cipbits%2Cexpire%2Cid%2Citag%2Csource%2Crequiressl%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cei%2Cinitcwndbps%2Cmime%2Cratebypass%2Cdur%2Clmt&signature=27FA794E9C44FCA164E0C66D1D5F1F5B4A41ABF2.30BE827C77F246DD3FE9C6397C63DBFBC174FB08&key=yt8"

Cannot read file.

**Comment by dhaniYanuar** [comment]
> I m trying to play Player.unity scene but i get error
> 
> NotSupportedException: No supported streams in youtube video '1PuGuqpHQGo'
> YoutubePlayer.YoutubePlayer+d__9.MoveNext () (at Assets/YoutubePlayer/Scripts/YoutubePlayer.cs:67)
> UnityEngine.Debug:LogException(Exception)
> YoutubePlayer.d__9:MoveNext() (at Assets/YoutubePlayer/Scripts/YoutubePlayer.cs:81)
> UnityEngine.UnitySynchronizationContext:ExecuteTasks()
> 
> I need to play stream video from youtube!

i still have same problem here.

**Comment by iBicha** [comment]
Hi,
I recently made an update to this repo #10 
Feel free to try it and see if it solves this problem.
Cheers.

**Comment by iBicha** [comment]
Please reopen if problem persists.
