### ISSUE TITLE
[WebGL] CORS Missing allow origin 

### ISSUE THREAD

**Issue by markdimi** [iBicha/UnityYoutubePlayer#40]
Hello. 
I am having the following error while trying to show a video on WebGL. Any idea how to bypass this? 
Could you maybe add a header to the request in order for the server to properly fetch the video?

**Comment by iBicha** [comment]
WebGL support is tricky https://github.com/iBicha/UnityYoutubePlayer/issues/16#issuecomment-743368108
youtube-dl-server already has [cors](https://github.com/iBicha/youtube-dl-server/blob/9308a8f78245cb762564dfa154d312e0df86cd56/src/app.ts#L8)
The actual server rejecting your origin is youtube's.

**Comment by markdimi** [comment]
The player works great in the standalone version (Windows). It's a pitty it doesn't in WebGL.

**Comment by iBicha** [comment]
Added note to readme that WebGL is not supported. Closing

**Comment by FireBlast2020** [comment]
Why does it work perfectly on linux windows and mac but on android it doesnt work
