### ISSUE TITLE
[WebGL] JsonSerializationException

### ISSUE THREAD

**Issue by DefaultV** [iBicha/UnityYoutubePlayer#42]
Building a Unity project with WebGL as target, having the YoutubePlayer playing a simple URL on awake (Working in Editor) provides a black screen in the build and the following in the target console:

![image](https://user-images.githubusercontent.com/14123880/113877066-3db14c80-97b0-11eb-83ca-65217ccb0bd6.png)

Video used:
https://www.youtube.com/watch?v=eo8apVpcrIc

Unity export uses brotli compression with stripped engine code.
Adding a constructor manually by embedding the package also provides same error. Code is as following in the YoutubeVideoMetadata.cs:

```

[JsonConstructor]
public YoutubeVideoMetaData(string Title, string Url, string Extension, YoutubeVideoFormat[] requestedFormats, YoutubeVideoFormat[] Formats, string FileName) {
    this.Title = Title;
    this.Url = Url;
    this.Extension = Extension;
    this.requestedFormats = requestedFormats;
    this.Formats = Formats;
    this.FileName = FileName;
}
```

Will gladly provide more info if needed!

**Comment by iBicha** [comment]
This might be a separate issue, but before digging further into it, it's worth mentioning that WebGL is not supported because of CORS. See #40

**Comment by iBicha** [comment]
On another note, I suspect that your constructor is being stripped out, because the compiler doesn't see where it's being used.

**Comment by DefaultV** [comment]
Hey again! Thanks for the quick response!
Building with no stripping and adding constructors indeed removed the error, thanks for the heads-up!

**Comment by whynames** [comment]
Hey can you explain how did you make it work in Webgl?
