### ISSUE TITLE
Problem package with Unity 2018

### ISSUE THREAD

**Issue by RayosElDev** [iBicha/UnityYoutubePlayer#44]
Hello,
I wanna use this package with unity 2018 to use with VR
 in 2019 works Fine
but 2018 Unity
appear this;

Multiple precompiled assemblies with the same name nunit.framework.dll included or the current platform unity

**Comment by iBicha** [comment]
I don't think this is a UnityYoutubePlayer issue, since it doesn't use NUnit

**Comment by RayosElDev** [comment]
I saw the solved.
Its problem for dependencies of Unity Version.

**Comment by iBicha** [comment]
Do you mean the problem is solved? Or can you confirm that this is a UnityYoutubePlayer issue?

**Comment by RayosElDev** [comment]
Yes, it is solve.
in 2019 works good
in 2018 you have to adjust dependencies. just that
sorry
