### ISSUE TITLE
Legacy Example: TransientFailureException: Video watch page is broken. In most cases, this error indicates that the problem is on YouTube's side and this is not a bug in the library. To resolve this error, please wait some time and try again. If this issue persists, please report it on the project's GitHub page.

### ISSUE THREAD

**Issue by mhadji05** [iBicha/UnityYoutubePlayer#47]
Legacy Example:

no changes just download and play it.

TransientFailureException: Video watch page is broken.
In most cases, this error indicates that the problem is on YouTube's side and this is not a bug in the library.
To resolve this error, please wait some time and try again.
If this issue persists, please report it on the project's GitHub page.

Please let me know what can I do to fix it.

Thanks.

**Comment by iBicha** [comment]
I suggest updating to the latest version of https://github.com/Tyrrrz/YoutubeExplode and see if the problem persists. If the issue is still there, I would seek support from https://github.com/Tyrrrz/YoutubeExplode

**Comment by mhadji05** [comment]
I update to the latest version but the issue is still there.

Please let me know how can I fix it.

Thanks.
