### ISSUE TITLE
Install dependencies

### ISSUE THREAD

**Issue by mhadji05** [iBicha/UnityYoutubePlayer#48]
Please give us specific instructions what other packages must import to this LEGACY UnityYoutubePlayer to run it.

I have downloaded the following 3 packages in the Asset folder but there are a lot of errors

https://github.com/Tyrrrz/YoutubeExplode
https://github.com/AngleSharp/AngleSharp
https://assetstore.unity.com/packages/tools/input-management/json-net-for-unity-11347

Please let me know how to run this project.
Thank you.

**Comment by iBicha** [comment]
See https://github.com/iBicha/UnityYoutubePlayer/issues/49#issuecomment-851567075
Let's keep a single issue to track Legacy and avoid noise. Thanks
