### ISSUE TITLE
Unity Youtube Player (LEGACY) is not working

### ISSUE THREAD

**Issue by mhadji05** [iBicha/UnityYoutubePlayer#49]
UnityYoutubePlayer (LEGACY) is not working.

Please let me know the procedure I need to follow to run this project or if it has a problem and when will be fixed or how can i fix it.

Thank you in advance!

**Comment by iBicha** [comment]
The legacy version has not been updated in quite some time, and I'm not up to date on what needs to be done.
I personally do not have the time to maintain it, but if someone from the community wants to take charge of that, that's fine

**Comment by mhadji05** [comment]
Please can you give us instruction how can we update the dependencies such as: Youtube Explode, AngleSharp, etc.
Maybe this fixing the problem but i don't know how to do it. I tried it but many files missing so i have a lot of errors and warnings.

Please let us know!

**Comment by mhadji05** [comment]
Please can someone give me instruction how can I update Youtube Explode and nuget?

Thank you in advance!

**Comment by shaked6540** [comment]
You need to right click the project in visual studio->manage nuget packages, then update only YoutubeExplode. There will probably be breaking changes, so you will have to fix them before you can compile the project

**Comment by mhadji05** [comment]
@shaked6540  Thanks for your response. I m trying to find manage nuget packages when I right clicked but it doesn't exist this option. Please be more specific where can I Find this option.

Thanks in advance.

**Comment by mhadji05** [comment]
@shaked6540 I went in visual studio Tools/NuGet package manager Manage NuGet packages for solution... and I searched for youtube explode by Tyrrrz and updated youtubeExplode .

I'm still getting this error:

HttpRequestException: 404 (Not Found)
System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode () (at <7ebf3529ba0e4558a5fa1bc982aa8605>:0)
System.Net.Http.HttpClient+<GetStringAsync>d__52.MoveNext () (at <7ebf3529ba0e4558a5fa1bc982aa8605>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () (at <567df3e0919241ba98db88bec4c6696f>:0)
YoutubeExplode.YoutubeClient+<GetVideoInfoParserAsync>d__10.MoveNext () (at Assets/_CompleteProject/_YoutubeNeeds/YoutubeExplode/YoutubeClient.cs:47)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () (at <567df3e0919241ba98db88bec4c6696f>:0)
YoutubeExplode.YoutubeClient+<GetPlayerResponseParserAsync>d__11.MoveNext () (at Assets/_CompleteProject/_YoutubeNeeds/YoutubeExplode/YoutubeClient.cs:55)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () (at <567df3e0919241ba98db88bec4c6696f>:0)
YoutubeExplode.YoutubeClient+<GetVideoMediaStreamInfosAsync>d__38.MoveNext () (at Assets/_CompleteProject/_YoutubeNeeds/YoutubeExplode/YoutubeClient.Video.cs:85)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <567df3e0919241ba98db88bec4c6696f>:0)
YoutubePlayer.highYoutubePlayer+<PlayVideoAsync>d__11.MoveNext () (at Assets/_CompleteProject/_YoutubeNeeds/YoutubePlayer/Scripts/highYoutubePlayer.cs:82)
UnityEngine.Debug:LogException(Exception)
YoutubePlayer.<PlayVideoAsync>d__11:MoveNext() (at Assets/_CompleteProject/_YoutubeNeeds/YoutubePlayer/Scripts/highYoutubePlayer.cs:129)
UnityEngine.UnitySynchronizationContext:ExecuteTasks() (at C:/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:104)

**Comment by shaked6540** [comment]
Youtube explode is working fine, if you're still getting errors its either because the old project doesn't support it or you didn't update it correctly

**Comment by mhadji05** [comment]
Did you try run Unity Youtube Player (LEGACY) for 360 videos?
Did you achieve to run it successfully?

**Comment by shaked6540** [comment]
No, I never used this project before so I can't help you with that. If youtube explode isn't working you should open an issue in the youtube explode repository and not here

**Comment by iBicha** [comment]
See #52 which updates to use NuGet for Unity.
I tried the sample scene and it's working fine, except for captions.
Try that branch, and if that works for you, I can merge it.

**Comment by iBicha** [comment]
Merged #52 
Reopen if that doesn't fix it
Thanks

**Comment by mhadji05** [comment]
I could not make it work. A video or file showing step by step the process might help.

**Comment by iBicha** [comment]
1. Pull branch `legacy/youtube-explode`
2. Open the Unity project in Unity
3. Open `Assets/YoutubePlayer/Scenes/Player` scene
4. Press play.

- The video should play fine
- You might see a 404 error in the console, and the subtitles won't play

**Comment by mhadji05** [comment]
I also want to play subtitles. Is there a way to fix the problem so that the subtitles are displayed?

**Comment by iBicha** [comment]
That needs to be fixed on the YouTubeExplode side.
They would need to publish a new version, and update it here.
