### ISSUE TITLE
ArgumentNullException: Value cannot be null.

### ISSUE THREAD

**Issue by mhadji05** [iBicha/UnityYoutubePlayer#5]
Hello,

Some links is ok but with some others youtube links i take this error

e.g: https://www.youtube.com/watch?v=QKm-SOOMC4c

ArgumentNullException: Value cannot be null.

Parameter name: value
Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull (System.Object value, System.String parameterName) (at C:/Users/bhadriche/Desktop/Tag AR/Assets/JsonDotNet/JsonDotNet201Source~/Source/Newtonsoft.Json/Utilities/ValidationUtils.cs:38)
Newtonsoft.Json.Linq.Extensions.Value[T,U] (System.Collections.Generic.IEnumerable`1[T] value) (at C:/Users/bhadriche/Desktop/Tag AR/Assets/JsonDotNet/JsonDotNet201Source~/Source/Newtonsoft.Json/Linq/Extensions.cs:174)
Newtonsoft.Json.Linq.Extensions.Value[U] (System.Collections.Generic.IEnumerable`1[T] value) (at C:/Users/bhadriche/Desktop/Tag AR/Assets/JsonDotNet/JsonDotNet201Source~/Source/Newtonsoft.Json/Linq/Extensions.cs:162)
YoutubeExplode.YoutubeClient+<GetPlayerConfigurationAsync>d__37.MoveNext () (at Assets/YoutubeExplode/YoutubeClient.Video.cs:80)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <7d97106330684add86d080ecf65bfe69>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <7d97106330684add86d080ecf65bfe69>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <7d97106330684add86d080ecf65bfe69>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <7d97106330684add86d080ecf65bfe69>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <7d97106330684add86d080ecf65bfe69>:0)
YoutubeExplode.YoutubeClient+<GetVideoMediaStreamInfosAsync>d__41.MoveNext () (at Assets/YoutubeExplode/YoutubeClient.Video.cs:362)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <7d97106330684add86d080ecf65bfe69>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <7d97106330684add86d080ecf65bfe69>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <7d97106330684add86d080ecf65bfe69>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <7d97106330684add86d080ecf65bfe69>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <7d97106330684add86d080ecf65bfe69>:0)
YoutubePlayer.YoutubePlayer+<PlayVideoAsync>d__9.MoveNext () (at Assets/YoutubePlayer/Scripts/YoutubePlayer.cs:64)
UnityEngine.Debug:LogException(Exception)
YoutubePlayer.<PlayVideoAsync>d__9:MoveNext() (at Assets/YoutubePlayer/Scripts/YoutubePlayer.cs:81)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
YoutubeExplode.<GetVideoMediaStreamInfosAsync>d__41:MoveNext() (at Assets/YoutubeExplode/YoutubeClient.Video.cs:588)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
YoutubeExplode.<GetPlayerConfigurationAsync>d__37:MoveNext() (at Assets/YoutubeExplode/YoutubeClient.Video.cs:190)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult(IHtmlDocument)
YoutubeExplode.<GetVideoEmbedPageHtmlAsync>d__35:MoveNext() (at Assets/YoutubeExplode/YoutubeClient.Video.cs:58)
UnityEngine.UnitySynchronizationContext:ExecuteTasks()

**Comment by mhadji05** [comment]
hi again,

Maybe i understand what happen. if the video is a different type of .mp4 fault parsed to googlevideo.
if you can help with that i appreciate it a lot.

thanks.

**Comment by top-man** [comment]
Same issue here.
Here is the video link.
https://www.youtube.com/watch?v=iMSMnYI4gSM
@iBicha  when can I expect the updated version?
Our team is using your plugin for our several projects and we should resolve this issue asap.

**Comment by mhadji05** [comment]
> Same issue here.
> Here is the video link.
> https://www.youtube.com/watch?v=iMSMnYI4gSM
> @iBicha when can I expect the updated version?
> Our team is using your plugin for our several projects and we should resolve this issue asap.

You need to convert your video to .mp4

**Comment by top-man** [comment]
I'd like to get a universal plugin that works with any type of videos on youtube.
[https://github.com/Tyrrrz/YoutubeExplode](YoutubeExplode) updated their api 4 days ago.
Can you please integrate the latest api and update your plugin?

**Comment by mhadji05** [comment]
Sorry but i am not owner or co-owner of this project. I use this project to create something i need. I had the same problem. you can update the Youtube explode plugin and find the public static class Extensions.
On method below you can change the type of video you need or you can make some changes to create a universal tool for every type of video:

`public static MuxedStreamInfo WithHighestVideoQualitySupported(this IEnumerable<MuxedStreamInfo> streamInfos)
        {
            if(streamInfos == null)
                throw new ArgumentNullException(nameof(streamInfos));
            return streamInfos
                .Where(info => info.Container == Container.Mp4)
                .Select(info => info).OrderByDescending(s => s.VideoQuality).FirstOrDefault();
        }`

**Comment by iBicha** [comment]
Hi guys,
I apologize for lack of activity on my side. I've been a bit busy, I do plan on updating this repo and improve things, but I do not have an ETA.
Pull requests are more than welcome in the meantime. Cheers

**Comment by 6ert** [comment]
I would like to contribute, if not comments like @top-man's wouldnt keep me from doing so...

**Comment by Bitgamey** [comment]
I am also receiving the ArgumentNullException error, but I appreciate what you have done with this project so far.  I wondered if it was the specific file format that might cause the error but I have 2 files (if you need examples) that are both MP4 and only 1 works, so I'm thinking maybe a specific codec is causing it?

Here are the 2 examples:
https://www.youtube.com/watch?v=pjnqfc3vQy4 (does work)
https://www.youtube.com/watch?v=6dzikBZTUy8 (doesn't work)

I will push forward including this in my project and hope it gets resolved soon! Thanks again.

**Comment by RC0D3** [comment]
It occurs because we need to decrypt some url video,the player do it...
If you see the json no have "url", only "cipher" with "s" and "url"...

see here more
https://stackoverflow.com/questions/21496126/android-youtube-download-url-403-forbidden

have 3 implemented modes, one in scala, one in python and one in csharp

In csharp is the best way, I think xD

**Comment by ZoraizQ** [comment]
Any updates regarding this? Has the YoutubeExplode plugin been updated?

**Comment by iBicha** [comment]
I would like to comment on how this doesn't support all the videos:
Yes, Youtube have mixed encodings, not all videos are encoded the same way.
The check for the MP4 container is a rough failsafe to get a video that Unity can play.
To learn more about supported videos, you can check https://docs.unity3d.com/Manual/VideoSources-FileCompatibility.html

Finally, I've updated this package in #10 , feel free to try it and see if it solves your problem.
Cheers
