### ISSUE TITLE
No audio on Windows 10

### ISSUE THREAD

**Issue by leon089y** [iBicha/UnityYoutubePlayer#54]
I use youtube player with Win10 and last version of unity. The video shows, but there is no sound. I use audio outputMode = Direct. What could be the reason?
![image](https://user-images.githubusercontent.com/65338598/123547791-cc5bb700-d76a-11eb-8cde-3c8f0947b872.png)

**Comment by iBicha** [comment]
Can you share the link to the video / your youtube player settings?

**Comment by leon089y** [comment]
Hello!
Link to the video - https://www.youtube.com/watch?v=1PuGuqpHQGo
Youtube Player attached to 3D object - Cube.
![image](https://user-images.githubusercontent.com/65338598/124237596-5cf61680-db20-11eb-9b25-174143a615ee.png)

**Comment by iBicha** [comment]
I cannot reproduce, but if I had to guess, maybe this is related to the [supported formats](https://docs.unity3d.com/Manual/VideoSources-FileCompatibility.html), and what kind of codecs you have installed.
I don't have Windows 10 to dig deeper into this

**Comment by iBicha** [comment]
I cannot reproduce on Win10. Please try updating windows, using a newer Unity version, and the newer version of the package.
Please reopen issue if it persists. Thank you!
