### ISSUE TITLE
Send audio to Audiosource

### ISSUE THREAD

**Issue by CDAfonso** [iBicha/UnityYoutubePlayer#7]
Hello!
Congratulations on your work. 
I'm using your plugin, but i cant send the audio to the AudioSource. Is it possible?

I assign the audiosource on the YoutubePlayer, but it doesn't work.

Thanks

**Comment by thislookshard** [comment]
Has there been any progress on this? I would love to implement this but need it to play through audio source

**Comment by PhilippUryas** [comment]
Add "Audio Source" in "YoutubePlayer" and add it to "AudioSource" in "VideoPlayer"

![image](https://user-images.githubusercontent.com/21991015/72721548-62121080-3b8d-11ea-9fa0-772882846e1c.png)

**Comment by thislookshard** [comment]
Is there a way to get all the audio samples at once? (with audioSource.clip.GetData) I'm wondering because I'm trying to do spectrum analysis on the clip

**Comment by iBicha** [comment]
As `PhilippUryas` mentioned, you can redirect the audio to an audio source. If you're not interested in rendering the video, you can set the `Render Mode` of the video player to API only (there still will be a bit of overhead, since the video is being decoded.)

Another option is to call `YoutubeExplode` Apis directly, might look like something like this:
```
var youtube = new YoutubeClient();
var streamManifest = await youtube.Videos.Streams.GetManifestAsync("bnsUkE8i0tU");

// highest bitrate audio-only stream
var streamInfo = streamManifest.GetAudioOnly().WithHighestBitrate();
if (streamInfo != null)
{
    // Get the actual stream
    var stream = await youtube.Videos.Streams.GetAsync(streamInfo);
    
    // Download the stream to file
    await youtube.Videos.Streams.DownloadAsync(streamInfo, $"video.{streamInfo.Container}");
}

You can see more on https://github.com/Tyrrrz/YoutubeExplode
Note that in this case, you will need to manage the decoding/playback of the audio stream yourself.

**Comment by iBicha** [comment]
For this specific issue, `PhilippUryas`'s answer should do the job. Feel free to open an issue for other use cases.
