### ISSUE TITLE
Download Speed

### ISSUE THREAD

**Issue by Eikthyr** [iBicha/UnityYoutubePlayer#76]
I'm constantly bothering you, but am I the only one with this problem? When I try to download or watch a video, my download speed does not exceed 90 kb.I tried to download video via firebase to see if the problem is in Unity.I downloaded it with my normal internet speed without any problems.

Could heroku be doing a restriction?

![Download](https://user-images.githubusercontent.com/84289107/137978743-b650d4cd-cdb4-496a-877f-e91c66169723.png)

**Comment by jeffries7** [comment]
I've also recently been having issues with videos and constant video buffering. I own a YT player plugin from the asset store, they seem to have addressed an issue similar to this:

`Fixed slow speed to play some videos (new youtube update)`

I'll take at how they've addressed this and post back later.

**Comment by iBicha** [comment]
Thanks a lot for reporting. Let's close this issue in favor of #74 so we can discuss under the same thread.
