### ISSUE TITLE
Multiple 360 mode support (OverUnder, SideBySide, 180)

### ISSUE THREAD

**Issue by Skinzart** [iBicha/UnityYoutubePlayer#78]
Hello dev, is it possible to make this type of 360 video work?
I have some sample 360 videos not working properly
OverUnder : https://youtu.be/OOx2c-IZA5Q
SideBySide : https://youtu.be/Fv1NhegZwGY
180 : https://youtu.be/_fBKszF1Y7Q

maybe we can detect the video projection type from the metadata and then change the shader we use?

**Comment by iBicha** [comment]
Yeah, it's tricky, as now the format returned to the player is not playable by the video player anymore.

**Comment by iBicha** [comment]
Multiple shaders based on metadata - sounds awesome, and the right solution probably, but I probably won't find time to dive into it anytime soon, so I will count on the community to contribute such feature

**Comment by iBicha** [comment]
Closing this since the feature for 360 has been removed in version 3.0.0 (please see [comment](https://github.com/iBicha/UnityYoutubePlayer/issues/108#issuecomment-2048609135))
I apologize for this "reset", if this feature is still important to you, please open a feature request for the 360
