### ISSUE TITLE
Can't start process on IL2CPP

### ISSUE THREAD

**Issue by WOLKYDJ** [iBicha/UnityYoutubePlayer#79]
youtube player is does not working. giving me this error

Win32Exception: ApplicationName='/var/folders/df/xbvq1ggn2ts0v0g3_bgn8gd40000gn/T/.../.../youtube-dl.exe', CommandLine='--dump-single-json -f "best" "https://www.youtube.com/watch?v=RcHJTZTrZGI​"', CurrentDirectory='', Native error= mono-io-layer-error (5)
System.Diagnostics.Process.StartWithCreateProcess (System.Diagnostics.ProcessStartInfo startInfo) (at <b5226d7672da4aeaa36d32bf1166a63b>:0)
System.Diagnostics.Process.Start () (at <b5226d7672da4aeaa36d32bf1166a63b>:0)
(wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
YoutubePlayer.LocalYoutubeDl.ReadProcessOutputAsync (System.String filename, System.String arguments, System.Threading.CancellationToken cancellationToken) (at Packages/com.ibicha.youtube-player/Runtime/YoutubeDl/LocalYoutubeDl.cs:104)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <695d1cc93cca45069c528c15c9fdd749>:0)
YoutubePlayer.LocalYoutubeDl+<GetVideoMetaDataAsync>d__1`1[T].MoveNext () (at Packages/com.ibicha.youtube-player/Runtime/YoutubeDl/LocalYoutubeDl.cs:34)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <695d1cc93cca45069c528c15c9fdd749>:0)
YoutubePlayer.YoutubeDl+<GetVideoMetaDataAsync>d__13`1[T].MoveNext () (at Packages/com.ibicha.youtube-player/Runtime/YoutubeDl/YoutubeDl.cs:51)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <695d1cc93cca45069c528c15c9fdd749>:0)
YoutubePlayer.YoutubePlayer+<GetRawVideoUrlAsync>d__14.MoveNext () (at Packages/com.ibicha.youtube-player/Runtime/YoutubePlayer.cs:64)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <695d1cc93cca45069c528c15c9fdd749>:0)
YoutubePlayer.YoutubePlayer+<PrepareVideoAsync>d__15.MoveNext () (at Packages/com.ibicha.youtube-player/Runtime/YoutubePlayer.cs:80)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.GetResult () (at <695d1cc93cca45069c528c15c9fdd749>:0)
YoutubePlayer.PrepareYoutubeVideo+<Prepare>d__2.MoveNext () (at Assets/YoutubePlayer/Scripts/PrepareYoutubeVideo.cs:17)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <695d1cc93cca45069c528c15c9fdd749>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:153)
UnityEngine.UnitySynchronizationContext:ExecuteTasks() (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)

**Comment by iBicha** [comment]
Can you provide some details (platform, unity version, etc)

**Comment by WOLKYDJ** [comment]
PC/Mac and 2021.20.1

**Comment by iBicha** [comment]
Are you running in IL2CPP on desktop?

**Comment by Gama-Tech** [comment]
I'm also having this issue.

YouTube playback works in the Editor, but not in the Build. 
I'm using Unity 2021.3.3f1, and the build is targeting Windows and is compiling using IL2CPP.

**Comment by Gama-Tech** [comment]
Thanks for the follow up, setting `YoutubeDl.UseLocalInstance` to false is a viable work around for me.
