### ISSUE TITLE
Linux support 

### ISSUE THREAD

**Issue by markdimi** [iBicha/UnityYoutubePlayer#8]
Greetings

I tried using your plugin on my machine that runs linux (ubuntu 18:04) but I am getting an error:
```
Can't play movie [https://r7---sn-vuxbavcx-n3bl.googlevideo.com/videoplayback?expire=1592843188&ei=VIfwXtfOONuV1gKdlLrQDw&ip=2a02%3A587%3A6418%3A9e00%3A9c3%3Ae959%3A8495%3Ae129&id=o-ANPOBvZnZVTyuE-nPI3pPlcWxiFI-7w4Fe1KwJbV5B6A&itag=22&source=youtube&requiressl=yes&mh=lc&mm=31%2C29&mn=sn-vuxbavcx-n3bl%2Csn-4g5ednls&ms=au%2Crdu&mv=m&mvi=6&pl=38&initcwndbps=763750&vprv=1&mime=video%2Fmp4&ratebypass=yes&dur=4634.261&lmt=1592707272793616&mt=1592821474&fvip=5&c=WEB&txp=5432432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgKvNedXV3_LtjdemWCecpQiXMi9nqgQm-Z9t4MTCZmgACIQChp8gUkA3jm5RJv1iflVYMXzYJGkUsFpLrLkmtF8PhIQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAOzGkRV19TsGJlFNO3eyT2Onc_emtxvjG59PTz9m6v_hAiA1jwPNMILDZloH_eWga7hLsq3vVYAplwRnAiGDeD8AOA%3D%3D]
UnityEngine.Video.VideoPlayer:set_url(String)
YoutubePlayer.<PlayVideoAsync>d__9:MoveNext() (at Assets/YoutubePlayer/Scripts/YoutubePlayer.cs:73)
UnityEngine.UnitySynchronizationContext:ExecuteTasks()
```

Any idea why this is happening?

Is it because unity video support is poor? (it only supports ogv, webm and vp8)

https://docs.unity3d.com/2020.2/Documentation/Manual/VideoSources-FileCompatibility.html

**Comment by iBicha** [comment]
It's very likely the reason. Have you tried the same video on different platform?

**Comment by markdimi** [comment]
I didn't have the luck yet. I am planning for it though.

**Comment by iBicha** [comment]
We should be able address this with #28 , and be able to select the format based on the format selection of youtube-dl https://github.com/ytdl-org/youtube-dl#format-selection

**Comment by iBicha** [comment]
Closing since we no longer use YoutubeExplode. Please open another issue if there's specific videos that don't play (perhaps we can tweak youtube-dl options to get these videos to play properly in Unity)
