### ISSUE TITLE
The 360 video application no longer works

### ISSUE THREAD

**Issue by ktfk94** [iBicha/UnityYoutubePlayer#80]
After a few months of using the UnityYoutubePlayer without a problem, now is not working. The aplication gets 360 videos from youtube and plays it. It is done in Unity with Android.

From a 360 video of youtube it generates a URL like this one: 
https://rr2---sn-h5nhv8pa-cjos.googlevideo.com/videoplayback?expire=1643478019&ei=oyf1YcXvI8jSxwKixLWQCw&ip=93.176.147.217&id=o-AP9hazQEszpIWe6LZfAlWHtFMtwEpXZMYR5h4POEJP0U&itag=272&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C271%2C272%2C278%2C313&source=youtube&requiressl=yes&mh=zQ&mm=31%2C29&mn=sn-h5nhv8pa-cjos%2Csn-h5q7knee&ms=au%2Crdu&mv=m&mvi=2&pl=21&initcwndbps=1845000&vprv=1&mime=video%2Fwebm&ns=hiQttHJWQzg6__po0H-4_TUG&gir=yes&clen=88669427&dur=61.327&lmt=1623085628288900&mt=1643455985&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=6211222&n=TQyeMv-qYvVTIrnjtJU&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAMo08O5Ybmctr3vNHTd_V340ZcRfNUaLRtHyQdQZMzzoAiACtKo7Qpda70fZowXXl8un0OdcULIrrZL638xwbMAVdw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgcP2q_NYtdUyOUunyJOXrB-5iOKx41LIoqNaIy6wOuzACIQCZgT-dNe6LKxetipDEOe-FD7cAu9pgs68-x_W-vR9RVg%3D%3D

It shows this error: WindowsVideoMedia error 0x80004004

If I use this URL in my google chrome it works but now it doesn't work anymore when I use it in a videoPlayer. What have changed and what can I do to fix this problem?

The version used when all was working was 1.4.

Thank you very much!

**Comment by ktfk94** [comment]
Changed the version to 2020.3.15f2 and still gets the same error

**Comment by iBicha** [comment]
Yeah, tricky.
We used to feed youtube-dl an empty user-agent, and set the video to about 1080p, and that roughly works.
This is a risk with using unofficial youtube stuff, it can break anytime.

**Comment by iBicha** [comment]
Released v2.0.1, which should fix 360 (at least the 360 demo scene works)
The audio still does not work.

**Comment by iBicha** [comment]
If this fixes the issue, feel free to close!

**Comment by SYBIOTE** [comment]
V2.0.1 only works with yt-dlp, and that gives a cannot open pyinstaller error, I just downloaded a proper release and placed that in the local app data folder, 
now I get this issue, please help 
JsonReaderException: Additional text encountered after finished reading JSON content: y. Path '', line 3, position 0.

**Comment by iBicha** [comment]
> its not working, i get this error using the latest LTS , with the master branch
> 
> JsonReaderException: Additional text encountered after finished reading JSON content: y. Path '', line 3, position 0.

I can't seem to reproduce the error, but I suspect that this happens because while yt-dlp returned a valid json, maybe it printed a warning or an error to the stderr stream. The package concatenates stdout and stderr before json parsing, which I realize now that it does not make sense.

If you can reproduce this issue consistently, please check if the fix #97 does the job or not.

**Comment by SYBIOTE** [comment]
all right thanks a lot, ill test out some other stuff and follow your recommendation

**Comment by iBicha** [comment]
As of right now, 360 seems to work.
Please feel free to comment/reopen or create a new issue if this is not the case

**Comment by jayaram9877** [comment]
#108  I guess its the same issue
