### ISSUE TITLE
Is must need to wait all video content downloaded before play it？

### ISSUE THREAD

**Issue by fengshaocheng2021** [iBicha/UnityYoutubePlayer#81]
Sorry my english is really poor. And im also a rookie about unity. I'd like to know that it is must to wait all the video content be download before i can start to play it?  For example, when i load a video is about 1 hour long, its that means i should wait a very long time to prepare it ?

Hope u can give some advices. It would be better if we can play while loading in background async.

Thanks!

**Comment by iBicha** [comment]
No, it does not download the whole video, it will stream it. See the example scenes, they should help you get started.
