### ISSUE TITLE
does it work on android? and how to configure to not have problems with dll or future errors!

### ISSUE THREAD

**Issue by hen000** [iBicha/UnityYoutubePlayer#82]
does it work on android? and how to configure to not have problems with dll or future errors!

I can trust the package to build and deliver to creators I need a package like this for a small project to present (the 28th now) and the video can't take long to load this is one of the biggest problems!, the biggest problem is to have confidence that it will work without errors!

**Comment by iBicha** [comment]
If you need confidence that it will work without errors, do not use Youtube. Youtube can change the dynamics of its web player anytime, rendering any youtube player plugin broken.
Otherwise, it probably works fine on Android, using the youtube-dl-server.
