### ISSUE TITLE
local version use without server

### ISSUE THREAD

**Issue by ubergeekseven** [iBicha/UnityYoutubePlayer#83]
I was looking through the code in the files and see that you somehow have links to local exe use for the downloader application. I have not found where it looks for this though.

Is this functional? If so, I can just point to the location of the one I use now for local downloads instead of the old ytdownload that no longer works right.

I just rename the exe to youtube-dl.exe and use it like normal and it all works. If the unity code would allow this to pass through the same requests it does now, I would not have to rewrite all the code. Then I could just make this a dependency in my build and place it where it needs to be.

**Comment by iBicha** [comment]
So this is now functional (it seems) and both youtube-dl and yt-dlp.
They are saved to `Application.temporaryCachePath`
