### ISSUE TITLE
Change youtube url with script

### ISSUE THREAD

**Issue by DeveloperJake1** [iBicha/UnityYoutubePlayer#84]
How can I change the YoutubePlayer's url with script? I also need to know how to play/pause this with script.

**Comment by iBicha** [comment]
You can use `YoutubePlayer.PlayVideoAsync(url)` to load/prepare the video from Youtube.
To pause/resume, you can [VideoPlayer](https://docs.unity3d.com/ScriptReference/Video.VideoPlayer.html).Play / [VideoPlayer](https://docs.unity3d.com/ScriptReference/Video.VideoPlayer.html).Pause
