### ISSUE TITLE
youtube-dl existed with code-1073741701

### ISSUE THREAD

**Issue by Muhammad-Asim-Dev** [iBicha/UnityYoutubePlayer#90]
sir in youtube playlist this error comes up please provide any solution

**Comment by iBicha** [comment]
Can you share more information? (Package version, OS, platform, etc)

**Comment by Muhammad-Asim-Dev** [comment]
Pakage version V2.0.0
WIndow
Platform unity

**Comment by iBicha** [comment]
I was investigating, and there was an issue with showing error message. Everyone was seeing error codes only.
Please try V2.0.1.
Thanks
